networks:
  network:
    driver: bridge
    external: false

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - network

  postgres:
    image: postgres:17.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: B100dy50.waf!
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d db']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:
  pgdata:
  node_modules:
